### ISSUE TITLE
Production builds break in 5.0.0-0

### ISSUE THREAD

**Issue by jacobq** [mansona/ember-cli-notifications#254]
Steps to reproduce:

1. `ember new junk-app` (used ember-cli 3.14.0)
2. `ember install ember-cli-notifications@5.0.0-0`
3. `ember build -e production` --> fails

```
⠋ BuildingWARNING: Option "nodeWorker" is deprecated since workerpool@5.0.0. Please use "workerType" instead.
Environment: production
cleaning up...
Build Error (broccoli-persistent-filter:CleanCSSFilter) in assets/vendor.css

Cannot read property '0' of null


Stack Trace and Error Report: /tmp/error.dump.f1e37a734d7d87be1c77261885e680d7.log
```

<details><summary>Full log</summary>

```
=================================================================================

ENV Summary:

  TIME: Tue Dec 03 2019 13:20:10 GMT-0600 (Central Standard Time)
  TITLE: ember
  ARGV:
  - /home/user/.nvm/versions/node/v12.13.1/bin/node
  - /home/user/.nvm/versions/node/v12.13.1/bin/ember
  - build
  - -e
  - production
  EXEC_PATH: /home/user/.nvm/versions/node/v12.13.1/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/user/.nvm/versions/node/v12.13.1/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/local/games
  - /usr/games
  - ./node_modules/.bin
  - /home/user/.local/bin
  PLATFORM: linux x64
  FREEMEM: 3615854592
  TOTALMEM: 33701347328
  UPTIME: 70693
  LOADAVG: 1.94482421875,1.78271484375,1.7763671875
  CPUS:
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4023
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4012
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4079
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4008
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4026
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4001
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - llhttp: 1.1.4
  - modules: 72
  - napi: 5
  - nghttp2: 1.39.2
  - node: 12.13.1
  - openssl: 1.1.1d
  - tz: 2019c
  - unicode: 12.1
  - uv: 1.33.1
  - v8: 7.7.299.13-node.16
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property '0' of null
    at findNameRoot (/home/user/tmp/junk-app/node_modules/clean-css/lib/selectors/extractor.js:66:59)
    at extract (/home/user/tmp/junk-app/node_modules/clean-css/lib/selectors/extractor.js:36:9)
    at restructure (/home/user/tmp/junk-app/node_modules/clean-css/lib/selectors/restructure.js:297:22)
    at optimize (/home/user/tmp/junk-app/node_modules/clean-css/lib/selectors/advanced.js:71:5)
    at minify (/home/user/tmp/junk-app/node_modules/clean-css/lib/clean.js:228:5)
    at whenSourceMapReady (/home/user/tmp/junk-app/node_modules/clean-css/lib/clean.js:135:7)
    at /home/user/tmp/junk-app/node_modules/clean-css/lib/clean.js:155:14
    at CleanCssPromise.CleanCSS.minify (/home/user/tmp/junk-app/node_modules/clean-css/lib/clean.js:127:42)
    at promisify (/home/user/tmp/junk-app/node_modules/clean-css-promise/index.js:31:9)
    at new Promise (<anonymous>)
  - code: [undefined]
  - codeFrame: Cannot read property '0' of null
  - errorMessage: assets/vendor.css: Cannot read property '0' of null
        in /tmp/broccoli-1293690lse2Mp2GT98/out-214-simple_concat_concat_concat_vendor_styles_assets_vendor_css
        at broccoli-persistent-filter:CleanCSSFilter
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: assets/vendor.css
    - line: [undefined]
    - treeDir: /tmp/broccoli-1293690lse2Mp2GT98/out-214-simple_concat_concat_concat_vendor_styles_assets_vendor_css
  - message: assets/vendor.css: Cannot read property '0' of null
        in /tmp/broccoli-1293690lse2Mp2GT98/out-214-simple_concat_concat_concat_vendor_styles_assets_vendor_css
        at broccoli-persistent-filter:CleanCSSFilter
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: broccoli-persistent-filter:CleanCSSFilter
  - originalErrorMessage: Cannot read property '0' of null
  - stack: TypeError: Cannot read property '0' of null
    at findNameRoot (/home/user/tmp/junk-app/node_modules/clean-css/lib/selectors/extractor.js:66:59)
    at extract (/home/user/tmp/junk-app/node_modules/clean-css/lib/selectors/extractor.js:36:9)
    at restructure (/home/user/tmp/junk-app/node_modules/clean-css/lib/selectors/restructure.js:297:22)
    at optimize (/home/user/tmp/junk-app/node_modules/clean-css/lib/selectors/advanced.js:71:5)
    at minify (/home/user/tmp/junk-app/node_modules/clean-css/lib/clean.js:228:5)
    at whenSourceMapReady (/home/user/tmp/junk-app/node_modules/clean-css/lib/clean.js:135:7)
    at /home/user/tmp/junk-app/node_modules/clean-css/lib/clean.js:155:14
    at CleanCssPromise.CleanCSS.minify (/home/user/tmp/junk-app/node_modules/clean-css/lib/clean.js:127:42)
    at promisify (/home/user/tmp/junk-app/node_modules/clean-css-promise/index.js:31:9)
    at new Promise (<anonymous>)

=================================================================================
```
</details>

<details><summary>Running with `DEBUG=*notif*`</summary>

```
- Building
Tue, 03 Dec 2019 19:27:29 GMT ember-cli-htmlbars:addon:ember-cli-notifications Colocation processing: false (hasOctane: false; hasValidEmberCLIVersion: true; hasValidBabelVersion: true;
Tue, 03 Dec 2019 19:27:30 GMT ember-cli-htmlbars:addon:ember-cli-notifications [treeFor(ember-cli-notifications - addon)#832] Colocation processing: false (hasOctane: false; hasValidEmberCLIVersion: true; hasValidBabelVersion: true;
WARNING: Option "nodeWorker" is deprecated since workerpool@5.0.0. Please use "workerType" instead.
- Building
- building... 
Tue, 03 Dec 2019 19:27:30 GMT broccoli-funnel:Funnel: ember-cli-notifications/addon build, { in: '0ms', linkedRoots: true, inputPath: '/home/user/tmp/junk-app/node_modules/ember-cli-notifications/addon', destPath: '/tmp/broccoli-129807eYO0SyPHPsfl/out-078-funnel_funnel_ember_cli_notifications_addon/ember-cli-notifications' }
Tue, 03 Dec 2019 19:27:30 GMT broccoli-persistent-filter:Babel > [Babel: ember-cli-notifications] [Babel: ember-cli-notifications#1567 -> derivePatches#1568] found 0 files invalidated due to dependency changes.
Tue, 03 Dec 2019 19:27:30 GMT broccoli-persistent-filter:Babel > [Babel: ember-cli-notifications] [Babel: ember-cli-notifications#1567 -> derivePatches#1568] derivePatches duration: 0.43 ms {"patches":17,"entries":17,"invalidations":{"dependencies":0,"count":0,"duration":"0.08 ms"},"walk":{"entries":17,"duration":"0.34 ms"}}
Tue, 03 Dec 2019 19:27:30 GMT broccoli-persistent-filter:Babel > [Babel: ember-cli-notifications] [Babel: ember-cli-notifications#1567 -> applyPatches#1569] applyPatches duration: 5.44 ms {"mkdir":8,"rmdir":0,"unlink":0,"change":0,"create":9,"other":0,"processed":6,"linked":3,"handleFile":9,"processString":6,"processStringTime":10804685,"persistentCacheHit":6,"persistentCachePrime":0,"handleFileTime":32026064}
- cleaning up
- cleaning up
Build Error (broccoli-persistent-filter:CleanCSSFilter) in assets/vendor.css

Cannot read property '0' of null


```

</details>

**Comment by jacobq** [comment]
I think it's caused by invalid CSS, e.g. SCSS-style nesting and `&` here:

https://github.com/mansona/ember-cli-notifications/blob/e957531e76bc6972c4c8f0a45e0ce3987b44961f/addon/styles/components/notification-message.css#L52-L55

https://github.com/mansona/ember-cli-notifications/commit/e957531e76bc6972c4c8f0a45e0ce3987b44961f#diff-fac9b32cb9d21b7e423ac28aa4d008feR52

**Comment by bjornharrtell** [comment]
Got this issue too, thanks for identifying it @jacobq.

**Comment by cah-brian-gantzler** [comment]
After the application of pr https://github.com/mansona/ember-cli-notifications/pull/258 I am now able to build, and the addon functions correctly when doing --environment=production

Thanks

**Comment by mansona** [comment]
I'm going to close this for now because we've had a few people confirm that the updates to the new version fixed the problem.  Let me know if it's still an issue for you and I can reopen 👍
