### ISSUE TITLE
Installation broken with Ember Octane Blueprint

### ISSUE THREAD

**Issue by ELepolt** [mansona/ember-cli-notifications#257]
```
ember new ember-quickstart -b @ember/octane-app-blueprint
cd ember-quickstart/
ember install ember-cli-notifications

Installing packages... This might take a couple of minutes.
npm: Installed ember-cli-notifications
Cannot read property 'ui' of undefined


Stack Trace and Error Report: /tmp/error.dump.e623d070e33cb904187d8ce501e6e10b.log
An error occurred in the constructor for ember-css-modules at /home/evan/Documents/Code/tmp/ember-quickstart/node_modules/ember-css-modules

An error occurred in the constructor for ember-cli-notifications at /home/evan/Documents/Code/tmp/ember-quickstart/node_modules/ember-cli-notifications

```

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'ui' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'ui' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'ui' of undefined
    at PackageInfo.dumpInvalidAddonPackages (/home/evan/Documents/Code/tmp/ember-quickstart/node_modules/ember-cli/lib/models/package-info-cache/package-info.js:366:22)
    at Class.discoverAddons (/home/evan/Documents/Code/tmp/ember-quickstart/node_modules/ember-cli/lib/models/addon.js:487:15)
    at Class.initializeAddons (/home/evan/Documents/Code/tmp/ember-quickstart/node_modules/ember-cli/lib/models/addon.js:505:10)
    at setupRegistryForEachAddon (/home/evan/Documents/Code/tmp/ember-quickstart/node_modules/ember-cli-preprocess-registry/preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (/home/evan/Documents/Code/tmp/ember-quickstart/node_modules/ember-cli-preprocess-registry/preprocessors.js:46:3)
    at Class.init (/home/evan/Documents/Code/tmp/ember-quickstart/node_modules/ember-cli/lib/models/addon.js:327:7)
    at Class.superWrapper [as init] (/home/evan/Documents/Code/tmp/ember-quickstart/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class.init (/home/evan/Documents/Code/tmp/ember-quickstart/node_modules/ember-css-modules/index.js:23:42)
    at Class.superWrapper [as init] (/home/evan/Documents/Code/tmp/ember-quickstart/node_modules/core-object/lib/assign-properties.js:34:20)
    at new CoreObject (/home/evan/Documents/Code/tmp/ember-quickstart/node_modules/core-object/core-object.js:9:15)
```

**Comment by mansona** [comment]
hey thanks for your report! can you please test the upcoming beta and see if it still causes an issue? you can see more info here https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340 but you can install it using `npm i ember-cli-notifications@next`

**Comment by ELepolt** [comment]
That works!

One note that I did find:

In your docs you have this line
`notifications: Ember.inject.service('notification-messages')`

In Ember-Octane that would turn into:
`@service('notification-messages') notifications;`

But that errors out: `Error: Assertion Failed: Attempting to inject an unknown injection: 'service:notification-messages'`

But it's happy with it just being this: 
`@service notifications;`

**Comment by mansona** [comment]
@ELepolt yes the docs will also update when that is merged 👍 you can see the updated docs here: https://deploy-preview-251--ember-cli-notifications.netlify.com/

**Comment by cah-brian-gantzler** [comment]
after pr https://github.com/mansona/ember-cli-notifications/pull/258 is now also worked when doing --environment=production

**Comment by mansona** [comment]
I'm going to close this for now because https://github.com/mansona/ember-cli-notifications/pull/251 is finally merged 👍 let me know if anyone has any more issues and we can get them fixed right away 💪

**Comment by rinoldsimon** [comment]
`Error: Assertion Failed: Attempting to inject an unknown injection: 'service:notification-messages'`

Code:
`initializer/inject-notifications.js`

```
export function initialize( application ) {
  ['controller', 'component', 'route'].forEach(injectionTarget => {
    application.inject(injectionTarget, 'notifications', 'notification-messages:service');
  });
}

export default {
  name: 'inject-notifications',
  initialize
};
```

Ember - 3.26.1
"ember-cli-notifications": "^6.3.4",

**Comment by mansona** [comment]
@rinoldsimon it looks like your issue isn't related to this one 🤔  the service name was updated in v5 to just `notifications` https://github.com/mansona/ember-cli-notifications/blob/master/CHANGELOG.md#500--2020-01-09

If you still have an issue can you open a new one?

**Comment by rinoldsimon** [comment]
But the docs aren’t updated. It still says notification-messages https://ember-cli-notifications.netlify.app/
