### ISSUE TITLE
font-awesome error when updating from 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by cesarizu** [mansona/ember-cli-notifications#52]
When I update the `ember-cli-notifications` to `2.1.0` from `2.0.0` I get the following error:

```
Merge error: file fonts/fontawesome-webfont.eot exists in /home/cesar/src/bootenv/bootenv-webapp/tmp/funnel-output_path-EswIeip1.tmp and /home/cesar/src/bootenv/bootenv-webapp/tmp/funnel-output_path-dLNYnfA4.tmp
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
Error: Merge error: file fonts/fontawesome-webfont.eot exists in /home/cesar/src/bootenv/bootenv-webapp/tmp/funnel-output_path-EswIeip1.tmp and /home/cesar/src/bootenv/bootenv-webapp/tmp/funnel-output_path-dLNYnfA4.tmp
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
  at mergeRelativePath (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:98:21)
  at mergeRelativePath (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:122:17)
  at /home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
  at lib$rsvp$$internal$$tryCatch (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)
```

I have `"font-awesome": "~4.4.0"` defined on my `bower.json` file. Is there anything I should change elsewhere to make this work? How can I start debugging this?

Thanks!

**Comment by ynnoj** [comment]
Hey @cesarizu. I've not encountered this issue on projects where we use the add-on. I'd recommend clearing your project dependency directories and a fresh install.

```
rm -rf node_modules bower_components dist tmp
ember install ember-cli-notifications
npm install
```

**Comment by cesarizu** [comment]
Thanks for your reply. I removed `ember-cli-notifications` from my packages.json, then tried the following:

```
rm -rf node_modules bower_components dist tmp
rm -rf ~/.npm/ember-cli-notifications
bower cache clean
ember install ember-cli-notifications
npm install
bower install
```

After running `ember serve` I got the same problem.

**Comment by cesarizu** [comment]
I think the problem is with `ember-cli-font-awesome`. If I remove it from `packages.json` then it works (but I loose the helpers provided by that addon).

It seems that `ember-cli-notifications <= 2.0.0` was not including by default the font-awesome files from the `bower-components` dir on the tree, but in 2.1 it started to do that, and now there's a conflict with `ember-cli-font-awesome`.

If I set `icons='bootstrap'` on the `environment.js` file then I loose the icons. There seems that there's no way to tell this addon not include the font-awesome icons. Maybe a better place to do that than in `environment.js` would be in `Brocfile.js` (or now `ember-cli-build.js`) as most addons expose their configuration.

I'll try to make a pull request to allow this and update this issue.

**Comment by Kilowhisky** [comment]
I am also stuck with this error and i don't have ember-cli-font-awesome installed. Just `"fontawesome": "~4.3.0",` from bower installed. 

This is the error i'm getting though. 

```
Path or pattern "bower_components/font-awesome/css/font-awesome.css" did not match any files
Error: Path or pattern "bower_components/font-awesome/css/font-awesome.css" did not match any files
    at Object.multiGlob (C:\Projects\GIT\sky-router-3\node_modules\ember-cli\node_modules\broccoli-kitchen-sink-helpers\index.js:203:13)
    at Class.module.exports.CachingWriter.extend._addFiles (C:\Projects\GIT\sky-router-3\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\simple-concat.js:82:13)
    at Class.module.exports.CachingWriter.extend.updateCache (C:\Projects\GIT\sky-router-3\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\simple-concat.js:50:12)
    at C:\Projects\GIT\sky-router-3\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\broccoli-caching-writer\index.js:92:34
    at lib$rsvp$$internal$$tryCatch (C:\Projects\GIT\sky-router-3\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Projects\GIT\sky-router-3\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (C:\Projects\GIT\sky-router-3\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:476:11)
    at lib$rsvp$asap$$flush (C:\Projects\GIT\sky-router-3\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by vst** [comment]
I think that #53 makes sense to solve this. Devs may want to configure the inclusion of fa.

**Comment by joedaniels29** [comment]
For the record You can also get this if you have included an addon in both your projects dependencies and a nested addon's dependencies. ember-cli will try to do everything twice and yield an error like in the comment at the top `Merge error: file fonts/fontawesome-webfont.eot exists in /home/cesar/src/bootenv/bootenv-webapp/tmp/funnel-output_path-EswIeip1.tmp and /home/cesar/src/bootenv/bootenv-webapp/tmp/funnel-output_path-dLNYnfA4.tmp`
