### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by miclip** [mansona/ember-cli-notifications#57]
Getting an error installing: 

```
C:\ember install ember-cli-notifications
version: 1.13.8
File: C:\WINDOWS\system32\cmd.exe
spawn-sync@1.0.13 postinstall: `node postinstall`
spawn C:\WINDOWS\system32\cmd.exe ENOENT
Error: spawn-sync@1.0.13 postinstall: `node postinstall`
spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

**Comment by miclip** [comment]
Got it working by changing the ember-cli-sass dependency to "ember-cli-sass": "^4.2.0"
