### ISSUE TITLE
Cannot load with latest version

### ISSUE THREAD

**Issue by Kilowhisky** [mansona/ember-cli-notifications#95]
When i bumped to the latest version `4.0.5`.  I get this error trying to run `ember serve`

```
The Broccoli Plugin: [CSSModules] failed with:
Error: ENOENT: no such file or directory, open 'C:\C:\Projects\GIT\APP\tmp\cssmodules-input_base_path-qhR6zwsN.tmp\0\modules\ember-cli-notifications\styles\globals.css'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at CSSModules.loadPath (C:\Projects\GIT\APP\node_modules\broccoli-css-modules\index.js:105:20)
    at CSSModules.fetchExports (C:\Projects\GIT\APP\node_modules\broccoli-css-modules\index.js:93:15)
    at Parser.fetchImport (C:\Projects\GIT\APP\node_modules\css-modules-loader-core\lib\parser.js:90:19)
    at C:\Projects\GIT\APP\node_modules\css-modules-loader-core\lib\parser.js:49:31
    at Root.each (C:\Projects\GIT\APP\node_modules\postcss\lib\container.js:130:22)
    at Parser.fetchAllImports (C:\Projects\GIT\APP\node_modules\css-modules-loader-core\lib\parser.js:47:11)
```

**Comment by ynnoj** [comment]
Hey, sorry about the troubles! I just released `4.0.6` which should fix this issue.

Let me know how it works out for you.

**Comment by Kilowhisky** [comment]
Still no joy. Same exact error. 

npm: 3.5.3
ember-cli: 2.7.0
node: 4.4.5
os: win32 x64

**Comment by ynnoj** [comment]
@Kilowhisky Track this at #100 please.
